---
title: "query_data_visualization"
output: html_document
---

# Load libraries
```{r warning=FALSE, message=FALSE}
library(DBI)
library(duckdb)
library(ggplot2)
library(tidyverse)
library(sysfonts)
library(magick)
library(showtext)
```

### Connect to database and read in tables
```{r}
# connect to DuckDB database
con <- dbConnect(duckdb::duckdb(), "data/processed/asthma_aqi_data_2020_2022.duckdb")

# tables
asthma <- dbReadTable(con, "asthma_emergencies")
aqi <- dbReadTable(con, "annual_aqi")
```
### Enable showtext_auto()
```{r}
# enable showtext 
showtext_auto()
```

### Load fonts
```{r}
# import google fonts
font_add_google(name = "Bebas Neue",
                family = "bebas")

font_add_google(name = "Oswald",
                family = "os",
                regular.wt = 200)
```

# Query data and join 
```{r}
asthma_ca_2020 <- asthma %>%
  filter(state == "California", year == 2020) # filter to CA 2020 data

aqi_ca_2020 <- aqi %>%
  filter(state == "California", year == 2020) # filter to CA 2020 data

ca_join_2020 <- inner_join( # join both aqi_ca_2020 and asthma_ca_2020 
  asthma_ca_2020,
  aqi_ca_2020,
  by = c("state","year","county")) %>%
     select(county, year, er_visits, max_aqi)

```

# Create small df of population sizes for counties that have data available and join
```{r}
population_data <- data.frame(
  county = c("Los Angeles", "San Diego", "Orange", "Riverside", "San Bernardino",
             "Sacramento", "Alameda", "Fresno", "Contra Costa", "San Joaquin"),
  population = c(10172951, 3298634, 3194332, 2442304, 2195611,
                 1584288, 1622188, 1017162, 1155025, 800965)
)

# merge with data from database
ca_join_2020_adjusted <- ca_join_2020 %>%
  inner_join(population_data, by = "county") %>%
  mutate(er_per_10k = (er_visits / population) * 10000)
```

# Bar chart of asthma ER visits and max AQI, adjusted by population size 
```{r}

ggplot(ca_join_2020_adjusted, aes(y = reorder(county, -er_per_10k), x = er_per_10k, fill = max_aqi)) +
  geom_col() +
  scale_fill_viridis_c(name = "Max AQI", option = "inferno", direction = -1) +
  labs(
    title = "What role did air quality play in asthma-related ER visits in 2020?",
    subtitle = "Poor air quality was likely NOT the main driver of high ER asthma visits in CA in 2020.",
    y = "County",
    x = "ER Visits per 10,000 Residents"
  ) +
  theme_minimal() +
  theme(text = element_text(family = 'os', color = 'black'),
      plot.title = element_text(family = 'bebas', color = '#a3386c'),
      plot.subtitle = element_text(family = 'bebas', color = 'black', size = 10),
        axis.title = element_text(family = 'bebas', color = 'black'),
      axis.text = element_text(family = 'os', color = 'black'),
        legend.text = element_text(family = 'os', color = 'black'),
      legend.title = element_text(family = 'bebas', color = 'black'))
 

```


